dist: xenial
language: python

install:
  - pip install pipenv --upgrade
  - pipenv install --dev

script:
  - pytest .

#after_success:
#  - codecov

cache: pip

jobs:
  include:
    - stage: test
      python: '3.8'
