version: 2.1

jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.8.5-browsers

    environment:
      PIPENV_VENV_IN_PROJECT: 1

    steps:
      - checkout

      - restore_cache:
          keys:
            - cc-venv-{{ checksum "Pipfile.lock" }}
            - cc-venv- # used if checksum fails
      - run:
          name: Setting up virtualenv
          command: |
            sudo pip install pipenv
            pipenv install --dev
      - save_cache:
          key: cc-venv-{{ checksum "Pipfile.lock" }}
          paths:
            - ./.venv/

      - restore_cache:
          keys:
            - cc-selenium-{{ checksum "selenium.jar" }}
            - cc-selenium- # used if checksum fails
      - run:
          name: Setting up Selenium
          command: |
            curl -O http://selenium-release.storage.googleapis.com/3.5/selenium-server-standalone-3.5.3.jar
            mv selenium-server-standalone-3.5.3.jar selenium.jar
      - save_cache:
          key: cc-selenium-{{ checksum "selenium.jar" }}
          paths:
            - ./selenium.jar

      - run:
          name: (Running Selenium)
          command: java -jar selenium.jar -log tests/functional/artifacts/selenium.log
          background: true
      - run:
          name: (Running Local Web Server)
          command: pipenv run python -m app
          background: true

      - run:
          name: Performing Tests
          command: |
            pipenv run pytest .

      - store_artifacts:
          path: tests/functional/artifacts/
          destination: tr1
      - store_test_results:
          path: tests/functional/artifacts/

workflows:
  main:
    jobs:
      - build-and-test
