version: 2.1

workflows:
  main:
    jobs:
      - build-and-test

jobs:
  build-and-test:
    context:
      - build-envs-01
      - docker-hub-creds

    docker:
      - image: circleci/python:3.8.5-browsers
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD

    steps:
      - checkout

      - restore_cache:
          keys:
            - cc-venv-{{ checksum "Pipfile.lock" }}
      - run:
          name: Setting up virtualenv
          command: |
            sudo pip install pipenv
            make venv-dev
      - save_cache:
          key: cc-venv-{{ checksum "Pipfile.lock" }}
          paths:
            - ./.venv/

      - restore_cache:
          keys:
            - cc-selenium-{{ checksum "./.circleci/selenium.link" }}
      - run:
          name: Setting up Selenium
          command: |
            test -f selenium.jar || curl -O $(cat ./.circleci/selenium.link)
            mv selenium-*.jar selenium.jar || exit 0
            test -f selenium.jar
      - save_cache:
          key: cc-selenium-{{ checksum "./.circleci/selenium.link" }}
          paths:
            - ./selenium.jar

      - run:
          name: (Running Selenium)
          command: java -jar selenium.jar -log tests/functional/artifacts/selenium.log
          background: true
      - run:
          name: (Running Local Web Server)
          command: make run
          background: true

      - run:
          name: Performing Tests
          command: |
            make test
